console.log("Hello")
/*
 📦 What is `package.json`?

`package.json` is like the heart of any Node.js / JavaScript project.

It contains:

 ✅ 1. Project Information

* Name
* Version
* Description
* Author
* License

 ✅ 2. Project Dependencies

All the packages (libraries) your project uses, like:

```json
"dependencies": {
  "express": "^4.18.2",
  "react": "^18.2.0"
}
```

The `^` means it can install future minor updates.

 ✅ 3. Scripts

You can create short commands:

```json
"scripts": {
  "start": "node index.js",
  "dev": "nodemon index.js"
}
```

 🧠 Simple Meaning:

It tells Node: “Yeh project kya hai, kaise chalega, aur kaunse packages chahiye.”

---

 🔒 What is `package-lock.json`?

This file is automatically generated when you install packages (`npm install`).

 Its job is to ensure:

 ✅ 1. Exact Versions Locked

If `package.json` says:

```json
"express": "^4.18.2"
```

This can install:

* 4.18.3
* 4.19.0
* etc.

But package-lock.json will lock it like:

```json
"express": "4.18.2"
```

So everyone on your team installs the exact same version.

 ✅ 2. Speeds up Installation

Because it keeps a cached structure of all dependency trees.

 ✅ 3. Tracks Sub-Dependencies

Example: Express → depends on other libraries
Those libraries have their own dependencies

`package-lock.json` stores all of that.

 🧠 Simple Meaning:

It tells Node: “Next time install exact same versions, warna project break ho sakta hai.”

---

 📌 Summary (1-line)

* `package.json` → List of packages you *want*.
* `package-lock.json` → Exact versions of packages you *actually installed*.
*/
var catMe = require('cat-me');
console.log(catMe());